import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: 'Helvetica',
  },
  section: {
    marginBottom: 10,
  },
  heading: {
    fontSize: 18,
    marginBottom: 10,
    color: '#14b8a6', // teal-500
  },
  text: {
    fontSize: 12,
    lineHeight: 1.6,
  },
});

export const PdfReport = ({ symptoms, suggestion }: { symptoms: string; suggestion: string }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.section}>
        <Text style={styles.heading}>🩺 AI Symptom Report</Text>
        <Text style={styles.text}>Generated by Aidvise</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.heading}>Reported Symptoms:</Text>
        <Text style={styles.text}>{symptoms}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.heading}>AI Suggestion:</Text>
        <Text style={styles.text}>{suggestion}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.text}>
          ⚠️ This AI response is informational only. Always consult a healthcare professional.
        </Text>
      </View>
    </Page>
  </Document>
);
